Adds P3 Handout
CMU-313/CMU-313.github.io pull request #81
Opened 2023-10-13 00:19 UTC by anudaweerasinghe

Adds handout for P3 - Continuous Integration and Deployment. Unlike last semester, we'll be using GCP Cloud Run instead of fly.io this semester... Deployment Instructions need playtesting.

- [ X ] GCP Deployment Instructions
- [ X ] Updated Handout
- [ ] Gradescope / Canvas assignments
- [ ] Google sheet for peer feedback (extra credit)
- [ ] Playtesting deployment instructions

2023-10-17 21:23 UTC, sophiajwitt commented on docs/projects/P3/deployment.md
> +2. Make sure Redis and selected, and click "Create Database"
Small typo in "Make sure Redis and selected"

2023-10-17 23:08 UTC, vasumv approved these changes
LGTM

2023-10-19 02:55 UTC, rohanpadhye requested changes

2023-10-23 14:49 UTC, rohanpadhye approved these changes
LGTM, thanks!

2023-10-23 23:46 UTC, merged