Adds Recitation 8
CMU-313/CMU-313.github.io pull request #83
Opened 2023-10-27 03:16 UTC by vasumv

Adds Recitation 8 for LLMs.

- [x] Add Handout (new recitation)
- [] Update Course Schedule

2023-10-27 17:24 UTC, anudaweerasinghe commented on docs/recitations/reci8-llms.md
> +5.  In your terminal, run `gcloud config set project PROJECT_ID`, where the `PROJECT_ID` is the ID of your NodeBB project.
Where can they find this `PROJECT_ID`?

2023-10-27 17:27 UTC, anudaweerasinghe commented on docs/recitations/reci8-llms.md
> +## Activity 1: Examine the Stanford Question Answering (SQuAD) Dataset (10 mins)
Change the titles on the notebook to match these headings.

2023-10-27 17:28 UTC, anudaweerasinghe commented on docs/recitations/reci8-llms.md
> +
Include an "Activity 0" where people download the notebook, and run the "Install Python Dependencies" section

2023-10-27 17:29 UTC, anudaweerasinghe commented on docs/recitations/reci8-llms.md
> +For one example, print out the context, question, and expected answer.
This seems to be already given, do you plan on removing it from the notebook?

2023-10-27 17:35 UTC, anudaweerasinghe commented on docs/recitations/reci8-llms.md
> +4.  In your terminal, run `gcloud auth login` and open the authentication URL that is displayed. Choose the account linked to the NodeBB project, and copy the verification code and paste it into the
I had to run `gcloud auth application-default login` to fix auth problems in cell containing `query_llm`.

Note: I used homebrew to install the gcloud cli

2023-10-28 17:01 UTC, anudaweerasinghe requested changes
Thanks Vasu, colab setup is much cleaner. Had no problems with setup/running the notebook.

Left some comments about dataset, and eval implementation.

2023-10-28 17:05 UTC, anudaweerasinghe commented on docs/recitations/reci8-llms.md
> +we will use [_cosine similarity_](https://en.wikipedia.org/wiki/Cosine_similarity).
Using [this](https://www.sbert.net/docs/quickstart.html#comparing-sentence-similarities) might actually be better. It's a much cleaner abstraction of computing cosine similarities on generated embeddings. We can use 'sentence-transformers/msmarco-distilbert-base-tas-b' as a the model.

2023-10-28 17:40 UTC, vasumv commented on docs/recitations/reci8-llms.md
> +The dataset contains a set of questions and answers to test a system for reading comprehension. Load in the dataset and understand the format.
good call

2023-10-30 19:46 UTC, vasumv commented on docs/recitations/reci8-llms.md
> +we will use [_cosine similarity_](https://en.wikipedia.org/wiki/Cosine_similarity).
Changed to use "contains" for this recitation, and added links to bert-score, sbert, GCP text embeddings.

2023-10-31 23:46 UTC, anudaweerasinghe approved these changes

2023-10-31 23:47 UTC, merged