P5 Draft
CMU-313/CMU-313.github.io pull request #91
Opened 2023-11-10 21:33 UTC by anudaweerasinghe

2023-11-11 20:19 UTC, sophiajwitt commented
LGTM

2023-11-13 19:46 UTC, rohanpadhye requested changes
In `projectfinal.md` under `## Individual Reflection & Peer Evaluations (20 pts)`, please also mention that "You may not make use of generative AI tools like ChatGPT to write this response".

2023-11-13 19:46 UTC, rohanpadhye commented on docs/projects/P5/2_projectfinal.md
> +Evidence that your changes have been accepted into the code base of the open source project in forms of links or screenshots. **Note: You can also send the merged PR link via Slack to Rohan Padhye by
Should this be 18th December? And instead of naming only me, say "the instructors (via Slack group DM or email to both)"

2023-11-13 19:46 UTC, rohanpadhye commented on docs/projects/P5/2_projectfinal.md
> +**Reflection** – due Tuesday, December 12th, 11:59pm
Let's make this due on Monday, December 11th as well so that it does not conflict with class presentations.

2023-11-13 19:46 UTC, rohanpadhye commented on docs/projects/P5/index.md
> +C) [**Individual Reflections**](/projects/P5/2_projectfinal) – 20 points – due Tuesday, December 12th, 11:59pm
Let's make this due on Monday, December 11th as well so that it does not conflict with class presentations.

2023-11-14 18:02 UTC, merged